#### SSH Menu ####


# Menu is now the same as Ansible. [Category] and then host listed below.
[webservers]
foo.example.com
bar.example.com

[dbservers]
one.example.com
two.example.com
three.example.com